// Book of Answers data. Keep English and Chinese arrays aligned by index.
window.BOOKS = {
  "classic": {
    "en": {
      "name": "The Book of Answers",
      "prompt": "Hold your question in mind, then reveal your answer.",
      "hint": "tap to reveal",
      "askBtn": "Ask the Book",
      "againBtn": "Ask Again",
      "ornament": "✦",
      "answers": [
        "Yes, but keep it simple",
        "No, not in its current form",
        "Wait until the facts stop moving",
        "Trust the part of you that feels calm",
        "The timing is almost right",
        "Ask for one more piece of evidence",
        "Choose the option that gives you room to breathe",
        "Do not confuse urgency with importance",
        "A small step will tell you enough",
        "Let the wrong door close",
        "The answer is kinder than you expect",
        "This needs courage, not speed",
        "Say less; observe more",
        "The practical choice is the wise one",
        "You already know what must change",
        "Do it only if you can do it honestly",
        "The risk is real, but manageable",
        "Step back before you step forward",
        "The answer improves when you rest",
        "Leave space for a better surprise",
        "This is a yes with boundaries",
        "This is a no with relief inside it",
        "The quiet option has strength",
        "Choose what you can sustain",
        "A direct conversation will change everything",
        "The missing detail matters",
        "Do not bargain with your peace",
        "The answer is not ready to be rushed",
        "You need fewer opinions, not more",
        "The old way will not carry the new life",
        "Make the decision smaller",
        "Someone has already shown you the truth",
        "The path clears when you stop forcing it",
        "Protect your time like it matters",
        "This is worth one careful attempt",
        "The answer is hiding in your hesitation",
        "Let it be easier than you planned",
        "The next step is the honest one",
        "Delay will make the choice for you",
        "Begin before certainty arrives",
        "Yes, but make it smaller first.",
        "Yes, if the quiet part of you agrees.",
        "Say yes to the next step, not the whole future.",
        "The green light is real; drive slowly.",
        "Accept the opening, then set the terms.",
        "It is a yes with a lock on the door.",
        "Go, but leave yourself an exit.",
        "Yes, if you can say it without explaining yourself to everyone.",
        "The chance is worth taking once, not worshiping forever.",
        "Take the invitation, but bring your discernment.",
        "The answer leans yes after one honest condition.",
        "Begin, but do not overpromise.",
        "Let yourself want it, then check the price.",
        "This is permission, not a command.",
        "Choose it if your shoulders drop when you imagine it.",
        "Yes, but keep your name on your own life.",
        "Give it one clear morning of courage.",
        "The door is open enough for one step.",
        "A cautious yes is still a yes.",
        "Let the answer be simple: try.",
        "No, especially if you already feel yourself shrinking.",
        "The answer is no; your relief knows before your logic does.",
        "Do not keep a door open just because you paid to stand there.",
        "Decline the version that needs you to betray your sleep.",
        "If it asks for your peace as a deposit, walk away.",
        "This is not refusal; it is protection.",
        "Let the wrong thing be disappointed in you.",
        "Stop before resentment becomes your only language.",
        "The cost is hidden because you are trying not to see it.",
        "No is the cleanest mercy here.",
        "Put it down without making a speech.",
        "If you need to become someone else to receive it, refuse.",
        "It has the shape of opportunity and the appetite of a trap.",
        "The answer is no until the facts stop changing their story.",
        "You do not owe loyalty to a path that keeps erasing you.",
        "Close it gently; slamming is optional.",
        "If the best part is the fantasy, the answer is no.",
        "Do not sign a contract with your panic.",
        "Let the silence after no teach you how free you are.",
        "This ending is allowed to be kind.",
        "Wait one sleep cycle before making it permanent.",
        "The answer needs daylight.",
        "Not yet; the room is still full of static.",
        "Give time a chance to reveal the missing edge.",
        "Delay is not avoidance if you use it to gather truth.",
        "Wait until the urgency stops pretending to be wisdom.",
        "The right answer is forming under the surface.",
        "Do not pull the fruit before it sweetens.",
        "Let tomorrow answer the part tonight cannot hold.",
        "This is a pause, not a punishment.",
        "More will be shown after the next honest question.",
        "Wait until your body and calendar agree.",
        "The answer will become less dramatic if you rest.",
        "Give the facts twenty-four hours to behave.",
        "Not now, but keep the door in view.",
        "Let the fog earn your patience.",
        "Your timing is not wrong; it is unfinished.",
        "The wise part of you is asking for one more clue.",
        "Sleep before certainty. Then decide.",
        "The delay is protecting something you have not named.",
        "Choose the path that still feels true when no one applauds.",
        "The smaller choice is the stronger one.",
        "Pick the option you can explain in one sentence.",
        "Follow the answer that does not need a costume.",
        "Choose what reduces the secret strain.",
        "The second option deserves a real look.",
        "Pick the thing you can sustain on an ordinary week.",
        "The practical answer is not less magical.",
        "Choose the door that does not require begging.",
        "Let your values vote before your fear does.",
        "The answer is in the option with fewer hidden apologies.",
        "Choose what makes the future less tangled.",
        "The first step matters more than the perfect map.",
        "Do the reversible thing first.",
        "Pick the honest inconvenience over the comfortable lie.",
        "The cleanest path will not flatter your ego.",
        "If both options hurt, choose the one that teaches.",
        "Choose the version that gives reality more room.",
        "The answer is under the option you keep dismissing as too simple.",
        "Move toward what can be repeated without self-contempt.",
        "Say the sentence you keep rehearsing.",
        "Ask directly, then believe the answer you receive.",
        "The truth will be awkward for five minutes and useful for months.",
        "Stop negotiating with what you already know.",
        "Tell the truth before it becomes a symptom.",
        "The answer changes when you remove the performance.",
        "Say less to the crowd and more to the person involved.",
        "Ask the question without decorating it.",
        "The missing conversation is the decision.",
        "Honesty will cost less than managing the secret.",
        "The answer is waiting inside the words you avoid.",
        "Let the fact be plain.",
        "Do not use politeness to hide from clarity.",
        "Name the real reason; the fake one is tired.",
        "The next honest sentence is enough.",
        "Ask once, cleanly, without fishing.",
        "The truth does not need to be cruel to be complete.",
        "Make the private knowing public enough to act on.",
        "Stop translating the obvious into maybes.",
        "The answer will respect you when you respect the facts.",
        "Put a fence around your yes.",
        "The boundary is not the problem; the reaction to it is the information.",
        "Keep the door open only if it has hinges on your side too.",
        "You can be generous without becoming available for everything.",
        "The answer asks for a limit, not a sacrifice.",
        "Protect the part of you that keeps showing up.",
        "Do not lend your future to someone else's confusion.",
        "Give less access until trust catches up.",
        "A kind no will save more than a resentful yes.",
        "The line you draw will reveal the room you are in.",
        "Keep one promise to yourself in the middle of this.",
        "Your energy is evidence.",
        "Stop making exceptions for patterns.",
        "Boundaries are how the answer stays usable.",
        "The right people will adjust to the truth.",
        "If it cannot survive a limit, it was not stable.",
        "Guard the beginning from too much exposure.",
        "You are allowed to disappoint a demand.",
        "The door may stay open; your whole house may not.",
        "Save some tenderness for yourself.",
        "The timing is almost right, but your pace matters.",
        "The opportunity is early; prepare instead of pouncing.",
        "When the pressure drops, the answer will stand up.",
        "The next season knows more than this one.",
        "Do it after the final missing fact arrives.",
        "You are not late; you are becoming accurate.",
        "The answer has a clock, but not the one you fear.",
        "Now is for gathering, not declaring.",
        "The window is open, but the weather is changing.",
        "Let the timing be intelligent, not dramatic.",
        "If it must happen today, ask why.",
        "The right moment will feel quieter than expected.",
        "Move before the choice is made for you.",
        "Wait too long and the answer becomes someone else's.",
        "The calendar is not the same as readiness.",
        "The season is asking you to finish what you started.",
        "The answer is ripe enough for a test.",
        "Do not confuse fast with aligned.",
        "A slow yes may arrive stronger than a rushed one.",
        "The time is close; simplify the preparation.",
        "Trust the calm signal, not the anxious replay.",
        "Your first instinct was useful; your second thought can refine it.",
        "Look for evidence where your body relaxes.",
        "The sign is not supernatural; it is consistent.",
        "Your intuition needs facts, not worship.",
        "The answer is where relief and responsibility meet.",
        "If your body keeps bracing, investigate.",
        "The pattern is louder than the promise.",
        "You have enough evidence to stop pretending you do not.",
        "Listen to the part of you that does not need drama.",
        "The clue is in what repeats.",
        "Do not call it intuition if it only appears when you panic.",
        "The evidence is small, but it is real.",
        "Your body is not the judge, but it is a witness.",
        "The answer becomes accurate when feeling meets fact.",
        "Notice what you defend before anyone attacks.",
        "The quiet certainty deserves respect.",
        "One strange coincidence is nothing; three is a map.",
        "Believe the pattern before the apology.",
        "The part of you that feels clear is not being naive.",
        "Do the smallest truthful thing today.",
        "Send the simple message.",
        "Clean the corner you keep avoiding.",
        "Make one call before you make one theory.",
        "Ask for the document.",
        "Write the first version badly.",
        "Take the walk, then decide.",
        "Remove one complication.",
        "Begin where the resistance is smallest.",
        "Make the choice reversible if you can.",
        "Turn the question into a calendar item.",
        "Test it in private before announcing it.",
        "Spend fifteen minutes on the real thing.",
        "The answer wants movement, not more weather reports.",
        "Do the next step before naming the whole journey.",
        "Choose one person to ask, not ten.",
        "Make the request clear enough to be refused.",
        "Start with the task that lowers the temperature.",
        "Put a date on the maybe.",
        "Make it smaller until it can move.",
        "The risk is real, but it is not the whole story.",
        "Protect the asset no one can replace: your attention.",
        "Do not gamble with borrowed certainty.",
        "The danger is not failure; it is pretending you learned nothing.",
        "Keep a backup plan that does not insult your courage.",
        "Let caution be a tool, not a throne.",
        "The red flag is useful even if it is inconvenient.",
        "Do not make fear your financial advisor.",
        "Risk belongs in the plan, not in the driver's seat.",
        "The worst-case story is asking for numbers.",
        "Check the exit before entering.",
        "If the risk cannot be named, slow down.",
        "Your fear is loud because it wants a job.",
        "Give the risk a chair, not the microphone.",
        "The safest answer is not always the smallest life.",
        "Prepare for the cost you hope you will not pay.",
        "The answer is not reckless; it is brave with a helmet.",
        "The warning matters, but so does the possibility.",
        "You can be careful without becoming closed.",
        "Protect the part that makes the choice worth making.",
        "Let the ending end cleanly.",
        "The old shape cannot hold the new answer.",
        "Leave before the lesson turns bitter.",
        "The door closing is not a verdict on your worth.",
        "Some losses are the price of becoming honest.",
        "Do not reopen it because silence feels unfamiliar.",
        "The goodbye is smaller than the self-betrayal would be.",
        "The past can be thanked without being obeyed.",
        "This ending is clearing a table you need.",
        "Let what expired stop asking for fresh devotion.",
        "The answer is not behind you anymore.",
        "Grieve it, then stop feeding it.",
        "The new life will not fit in the old apology.",
        "Let the chapter close with fewer explanations.",
        "A clean ending is also a beginning with manners.",
        "Stop asking the old road for new scenery.",
        "Release the version that only worked when you were less true.",
        "The break is not failure if it restores your breath.",
        "Something ends because something else needs oxygen.",
        "You can leave without hating the room.",
        "The answer is hiding in the ordinary thing you keep overlooking.",
        "The quiet door is not locked.",
        "A message will arrive through someone practical.",
        "The omen is not the bird; it is your reaction to the bird.",
        "Look under the task you keep calling boring.",
        "The third option is disguised as a delay.",
        "The answer will wear plain clothes.",
        "The key is in the question you did not ask.",
        "Something small will change the scale.",
        "The sign will not shout; it will repeat.",
        "Follow the thread that makes you curious, not frantic.",
        "The answer is beside the obvious one.",
        "Watch what happens when you stop pushing.",
        "The unexpected helper is not random.",
        "A closed door may be guarding your attention.",
        "The pattern is arranging itself.",
        "The next clue will be inconvenient and useful.",
        "You are asking the right question from the wrong doorway.",
        "The answer comes after the unnecessary detail is removed.",
        "The book says: lighter, cleaner, sooner.",
        "Decide from the part of you that has to live with it.",
        "Do not outsource this choice.",
        "Ask what love, money, time, and pride each want; then choose truth.",
        "The answer is not perfect, but it is usable.",
        "Make the brave choice boring enough to survive.",
        "The right answer will ask for maintenance.",
        "Stop waiting for certainty to do courage's work.",
        "Let the answer be tested by Tuesday.",
        "The wise move is the one that still works after the mood changes.",
        "Do not make a life out of proving a point.",
        "Your future self is asking for fewer loose ends.",
        "What you can repeat is more important than what you can announce.",
        "The answer is a practice, not a lightning strike.",
        "If it brings you back to yourself, follow it.",
        "The next move should make the room clearer.",
        "The question has matured; your answer should too.",
        "Choose the version that gives you fewer secrets.",
        "The answer is asking for dignity.",
        "Begin with respect for reality.",
        "You are ready enough to take one honest step."
      ]
    },
    "zh": {
      "name": "答案之书",
      "prompt": "心怀你的问题，然后揭晓你的答案。",
      "hint": "点击揭晓",
      "askBtn": "问问书",
      "againBtn": "再问一次",
      "ornament": "✦",
      "answers": [
        "可以，但保持简单",
        "不，以现在的形式还不行",
        "等事实不再变化时再决定",
        "相信内心那个平静的部分",
        "时机快到了",
        "再寻找一个关键证据",
        "选择那个让你能喘息的选项",
        "不要把紧急误认为重要",
        "迈出一小步，就会知道得够多",
        "让不合适的门关上",
        "答案比你想象的更温柔",
        "这需要勇气，不需要速度",
        "少说一点，多观察一点",
        "务实的选择就是明智的选择",
        "你已经知道什么必须改变",
        "只有能诚实地做，才去做",
        "风险是真实的，但可以管理",
        "向前之前，先退一步",
        "休息之后，答案会变好",
        "给更好的意外留一点空间",
        "这是一个需要边界的是",
        "这是一个带着轻松感的否定",
        "安静的选择也有力量",
        "选择你能长期承担的事",
        "一次直接的谈话会改变很多",
        "缺失的细节很重要",
        "不要拿你的平静去交换",
        "答案还不能被催促",
        "你需要更少的意见，而不是更多",
        "旧方法撑不起新生活",
        "把这个决定拆小一点",
        "有人已经把真相展示给你了",
        "当你停止强推，路会变清楚",
        "像珍惜重要之物一样保护时间",
        "这值得一次谨慎的尝试",
        "答案藏在你的迟疑里",
        "允许它比计划中更容易",
        "下一步是那个诚实的选择",
        "拖延会替你做出选择",
        "在确定感到来之前先开始",
        "可以，但先把它做小。",
        "可以，如果你内心安静的部分也同意。",
        "对下一步说可以，不必对整个未来承诺。",
        "绿灯是真的，但慢慢开。",
        "接受这个入口，然后定下条件。",
        "这是一个可以，但门上要有锁。",
        "去，但给自己留出口。",
        "可以，如果你不必向所有人解释自己。",
        "这个机会值得试一次，不值得永远供奉。",
        "接下邀请，但带上你的分辨力。",
        "答案偏向可以，只差一个诚实条件。",
        "开始，但不要过度承诺。",
        "允许自己想要它，然后看清代价。",
        "这是允许，不是命令。",
        "如果想到它时你的肩膀放松，就选它。",
        "可以，但把自己的名字留在自己的人生上。",
        "给它一个清醒早晨的勇气。",
        "门已经开到足够走一步。",
        "谨慎的可以，仍然是可以。",
        "让答案简单一点：试试看。",
        "不，尤其当你已经感觉自己在变小。",
        "答案是不；你的轻松比逻辑更早知道。",
        "不要只因为付出过，就一直站在那扇门前。",
        "拒绝那个需要你背叛睡眠的版本。",
        "如果它要你拿平静当押金，离开。",
        "这不是拒绝，这是保护。",
        "让错误的东西对你失望吧。",
        "在怨气变成你唯一的语言前停下。",
        "代价之所以藏着，是因为你正在努力不看见它。",
        "在这里，不是最干净的慈悲。",
        "放下它，不必发表演讲。",
        "如果你必须变成别人才能得到它，就拒绝。",
        "它长得像机会，却有陷阱的胃口。",
        "在事实停止改口之前，答案是不。",
        "你不欠一条不断抹掉你的路忠诚。",
        "温柔地关上它；要不要摔门随你。",
        "如果最好的部分只是幻想，答案就是不。",
        "不要和你的恐慌签合同。",
        "让拒绝之后的安静教你看见自由。",
        "这个结束可以是温柔的。",
        "睡一觉之后，再把它变成永久决定。",
        "答案需要白天。",
        "还不是时候；房间里还有太多杂音。",
        "给时间一个机会，让缺失的边缘显出来。",
        "如果你用延迟收集真相，它就不是逃避。",
        "等紧迫感不再假装成智慧。",
        "正确答案正在水面下成形。",
        "果子还没甜，不要急着摘。",
        "让明天回答今晚承受不了的部分。",
        "这是暂停，不是惩罚。",
        "下一个诚实问题之后，会有更多显现。",
        "等你的身体和日历达成一致。",
        "休息之后，答案会没那么戏剧化。",
        "给事实二十四小时，让它们表现一下。",
        "不是现在，但让那扇门留在视线里。",
        "让雾气值得你的耐心。",
        "你的时机不是错了，只是还没完成。",
        "你内在明智的部分正在要一个线索。",
        "先睡，再确定。然后决定。",
        "这个延迟正在保护某个你还没说出口的东西。",
        "选择那条没人鼓掌时仍然真实的路。",
        "更小的选择，反而更有力量。",
        "选那个你能用一句话解释的选项。",
        "跟随那个不需要伪装的答案。",
        "选择那个减少暗中消耗的东西。",
        "第二个选项值得认真看一眼。",
        "选那个你在普通一周里也能维持的东西。",
        "务实的答案并不会少一点魔力。",
        "选择那扇不需要乞求才打开的门。",
        "让你的价值先投票，不要让恐惧抢先。",
        "答案在那个暗中道歉更少的选项里。",
        "选择那个让未来不那么打结的东西。",
        "第一步比完美地图更重要。",
        "先做可逆的那件事。",
        "选择诚实的不方便，不选舒服的谎言。",
        "最干净的路不会讨好你的自尊。",
        "如果两个选项都会痛，选那个会教会你的。",
        "选择那个给现实更多空间的版本。",
        "答案在那个你一直嫌太简单的选项下面。",
        "走向那个可以重复、且不会自我厌恶的选择。",
        "说出你一直排练的那句话。",
        "直接问，然后相信你收到的答案。",
        "真话会尴尬五分钟，却有用好几个月。",
        "不要再和你已经知道的东西谈判。",
        "在真相变成症状之前，把它说出来。",
        "去掉表演之后，答案会改变。",
        "少对人群说，多对当事人说。",
        "问那个问题，不要装饰它。",
        "缺失的那场谈话，就是决定本身。",
        "诚实的成本会低于管理秘密。",
        "答案等在你回避的那些词里。",
        "让事实朴素地站出来。",
        "不要用礼貌躲避清晰。",
        "说出真正原因；假的那个已经累了。",
        "下一句诚实的话就够了。",
        "干净地问一次，不要试探。",
        "真相不必残忍，才能完整。",
        "让私下的知道变得足够公开，足以行动。",
        "不要再把明显的事翻译成也许。",
        "当你尊重事实，答案也会尊重你。",
        "给你的可以围上一圈栅栏。",
        "边界不是问题，对边界的反应才是信息。",
        "只有那扇门在你这边也有铰链时，才让它开着。",
        "你可以慷慨，但不必对一切开放。",
        "答案要的是限制，不是牺牲。",
        "保护那个一直愿意出现的自己。",
        "不要把未来借给别人的混乱。",
        "在信任追上来之前，减少进入你的权限。",
        "一个温柔的不，会比怨气里的可以拯救更多。",
        "你画下的线，会暴露你所在的房间。",
        "在这件事中，至少守住一个对自己的承诺。",
        "你的精力就是证据。",
        "不要再为模式开例外。",
        "边界让答案保持可用。",
        "对的人会适应真相。",
        "如果它经不起限制，它本来就不稳。",
        "保护这个开始，别太早暴露给太多人。",
        "你可以让一个要求失望。",
        "门可以开着，但你的整座房子不必开放。",
        "给自己留一点温柔。",
        "时机快对了，但你的速度也很重要。",
        "机会还早，先准备，不要猛扑。",
        "压力降下来时，答案会自己站起来。",
        "下一个季节知道得比这个季节多。",
        "等最后那个缺失事实到来之后再做。",
        "你不是晚了，你是在变准确。",
        "答案有时钟，但不是你害怕的那一个。",
        "现在适合收集，不适合宣布。",
        "窗开着，但天气正在变。",
        "让时机变得聪明，而不是戏剧化。",
        "如果它非得今天发生，问问为什么。",
        "正确时刻会比你想象中安静。",
        "在选择替你做决定之前行动。",
        "等太久，答案就会变成别人的。",
        "日历不等于准备好。",
        "这个季节正在要求你完成已经开始的事。",
        "答案已经熟到可以测试了。",
        "不要把快误认为对齐。",
        "慢一点的可以，可能比匆忙的可以更强。",
        "时间很近了，把准备简化。",
        "相信平静的信号，不要相信焦虑的重播。",
        "第一直觉有用，第二个念头可以修正它。",
        "在身体放松的地方寻找证据。",
        "征兆不神秘，它只是持续出现。",
        "你的直觉需要事实，不需要供奉。",
        "答案在轻松和责任相遇的地方。",
        "如果身体一直绷紧，就调查一下。",
        "模式比承诺更响。",
        "你已经有足够证据，可以停止假装没有。",
        "听听那个不需要戏剧的自己。",
        "线索在反复出现的东西里。",
        "如果它只在你慌的时候出现，就别叫它直觉。",
        "证据很小，但是真的。",
        "你的身体不是法官，但它是证人。",
        "感受遇见事实时，答案会变准确。",
        "留意那个还没人攻击，你就先防守的东西。",
        "安静的确定感值得尊重。",
        "一个巧合什么都不是，三个就是地图。",
        "先相信模式，再听道歉。",
        "那个感到清楚的你，并不天真。",
        "今天做最小的真事。",
        "发那条简单的信息。",
        "清理那个你一直回避的角落。",
        "在制造一个理论前，先打一通电话。",
        "去要那份文件。",
        "把第一版写得差一点也没关系。",
        "先去走一走，再决定。",
        "去掉一个复杂点。",
        "从阻力最小的地方开始。",
        "如果可以，让这个选择可逆。",
        "把问题变成日历上的一件事。",
        "在宣布之前，先私下测试。",
        "花十五分钟做真正的那件事。",
        "答案想要行动，不想再听天气报告。",
        "在命名整段旅程前，先做下一步。",
        "选一个人问，不要问十个。",
        "把请求说清楚，清楚到可以被拒绝。",
        "从那个能降温的任务开始。",
        "给那个也许写上日期。",
        "把它变小，直到它能动起来。",
        "风险是真的，但不是整个故事。",
        "保护那个没人能替代的资产：你的注意力。",
        "不要拿借来的确定感赌博。",
        "危险不是失败，而是假装自己什么都没学到。",
        "留一个不侮辱你勇气的备用计划。",
        "让谨慎做工具，不要让它坐王座。",
        "红旗即使不方便，也很有用。",
        "不要让恐惧当你的财务顾问。",
        "风险应该在计划里，不该坐驾驶座。",
        "最坏情况的故事正在要求数字。",
        "进入之前，先看出口。",
        "如果风险说不出名字，就慢下来。",
        "你的恐惧很吵，是因为它想要一份工作。",
        "给风险一把椅子，不要给它麦克风。",
        "最安全的答案不总是最小的人生。",
        "为那个你希望不会支付的代价做准备。",
        "答案不是鲁莽，而是戴着头盔的勇敢。",
        "警告重要，可能性也重要。",
        "你可以小心，而不必封闭。",
        "保护那个让选择值得发生的部分。",
        "让结束干净地结束。",
        "旧形状装不下新答案。",
        "在这堂课变苦之前离开。",
        "门关上，不是对你价值的判决。",
        "有些失去，是变诚实的价格。",
        "不要因为安静不熟悉，就重新打开它。",
        "告别比自我背叛小得多。",
        "可以感谢过去，而不必服从过去。",
        "这个结束正在清出你需要的桌面。",
        "让过期的东西停止索要新的忠诚。",
        "答案已经不在你身后了。",
        "为它难过，然后停止喂养它。",
        "新生活塞不进旧道歉里。",
        "让这一章带着更少解释合上。",
        "干净的结束，也是有礼貌的开始。",
        "不要再向旧路索要新风景。",
        "放开那个只有在你不够真实时才成立的版本。",
        "如果断开让你重新呼吸，它就不是失败。",
        "有些东西结束，是因为另一些东西需要氧气。",
        "你可以离开，而不必恨那个房间。",
        "答案藏在你一直忽略的普通事里。",
        "那扇安静的门没有锁。",
        "一个消息会通过务实的人抵达。",
        "征兆不是那只鸟，而是你看见鸟时的反应。",
        "去那个你一直嫌无聊的任务下面找。",
        "第三个选项伪装成了延迟。",
        "答案会穿着便服出现。",
        "钥匙在你没有问的问题里。",
        "一个小东西会改变比例。",
        "征兆不会喊叫，它会重复。",
        "跟随那个让你好奇、而不是让你发疯的线头。",
        "答案在明显答案的旁边。",
        "看看你停止推的时候会发生什么。",
        "意外的帮手并不随机。",
        "一扇关上的门，可能正在守护你的注意力。",
        "模式正在自己排列。",
        "下一个线索会不方便，也会有用。",
        "你在错误门口问对的问题。",
        "去掉不必要的细节之后，答案会来。",
        "书上说：更轻、更干净、更早一点。",
        "从那个必须和结果一起生活的自己出发决定。",
        "不要把这个选择外包。",
        "问问爱、钱、时间和自尊各想要什么；然后选择真相。",
        "答案不完美，但可用。",
        "把勇敢的选择做得足够普通，普通到能活下来。",
        "正确答案会要求维护。",
        "不要再等确定感来替勇气干活。",
        "让答案在周二之前接受测试。",
        "明智的动作，是情绪变了之后仍然成立的那个。",
        "不要把证明一个观点活成一生。",
        "未来的你正在请求少一点烂尾。",
        "你能重复的，比你能宣布的更重要。",
        "答案是一种练习，不是一道闪电。",
        "如果它把你带回自己，就跟随它。",
        "下一步应该让房间更清楚。",
        "问题已经成熟了，你的答案也该成熟。",
        "选择那个让你秘密更少的版本。",
        "答案正在要求体面。",
        "从尊重现实开始。",
        "你已经足够准备好，可以迈出诚实的一步。"
      ]
    }
  },
  "audit": {
    "en": {
      "name": "Audit Life",
      "prompt": "Think of your audit dilemma, then face the evidence.",
      "hint": "tap to consult",
      "askBtn": "Consult the Files",
      "againBtn": "Re-sample",
      "ornament": "§",
      "answers": [
        "Insufficient documentation — rejected",
        "Scope creep detected. Abort immediately.",
        "Consult your senior manager first",
        "Mark it immaterial and move on",
        "The audit committee will decide",
        "This finding is material",
        "Management has overridden the control",
        "Request additional supporting evidence",
        "Not within the defined scope",
        "A compensating control exists, allegedly",
        "The deadline has been extended again",
        "Escalate immediately",
        "That is a control gap, not your personality flaw",
        "Working as intended, per management",
        "The walkthrough tells a different story",
        "Recalculate, reconcile, repeat",
        "Your sample size is insufficient",
        "Exception noted. Document and move on.",
        "This requires a second review",
        "Flag for follow-up next quarter",
        "Management accepted the risk. Keep the receipt.",
        "It is immaterial, but write the memo anyway",
        "Put it in the parking lot with the other ghosts",
        "Ask IT, then ask where IT got that answer",
        "Remediation is expected next fiscal year",
        "You are out of scope again",
        "The spreadsheet is innocent until filtered",
        "Document everything. Trust carefully.",
        "That is a significant deficiency",
        "Close the books first, ask questions later",
        "The PBC list just grew again",
        "Reperformance required",
        "No exceptions noted, a rare miracle",
        "The evidence file is incomplete",
        "Three-way match failed",
        "Management representation received, finally",
        "Your finding will be disputed by management",
        "Send the confirmation and pray",
        "The SOX deadline waits for no one",
        "Coffee first. Audit second.",
        "Evidence first, confidence later.",
        "If the support file is blurry, the conclusion is too.",
        "A screenshot without a date is a rumor in formal wear.",
        "Ask for source data before the story gets charming.",
        "The PDF is locked because the truth fears Excel.",
        "Tie it to source or let it go.",
        "The file name says final; the metadata disagrees.",
        "If it came from memory, it belongs in a conversation, not a workpaper.",
        "The evidence is almost enough, which means it is not enough.",
        "Open the attachment before trusting the email.",
        "The support agrees only after filtering, which is not agreement.",
        "Save the trail before the trail disappears.",
        "The answer is in the tab nobody mentioned.",
        "If you cannot reperform it, do not romance it.",
        "The document exists; the evidence does not.",
        "Ask who prepared it and who was afraid to.",
        "A signature is not a control if nobody read the thing.",
        "The invoice has a vibe; get a date.",
        "Evidence should reduce drama, not create mythology.",
        "Put the source link where future you can find it.",
        "The PBC list has entered its villain era.",
        "Ask once clearly; chase twice only with manager blessing.",
        "The client did not forget; they prioritized your suffering.",
        "Send the request before noon if you want it before regret.",
        "PBC means Please Be Calm, allegedly.",
        "A polite follow-up is not harassment; it is audit weather.",
        "If the client says will send shortly, start a clock, not a prayer.",
        "The missing file is probably named New Folder 7.",
        "Accept the explanation only after it survives one follow-up.",
        "The client call needs an agenda and an exit ramp.",
        "If they answer everything except the question, escalate.",
        "The third reminder should come with bullets.",
        "Do not let charm substitute for support.",
        "The request is clear; the response is interpretive dance.",
        "Ask for one owner. Crowds do not upload evidence.",
        "The delay is a data point.",
        "A friendly client can still give unusable evidence.",
        "The answer is pending, which is audit for haunting.",
        "Put the request in writing before memory edits it.",
        "Today's PBC miracle will become tomorrow's review note.",
        "The control works if it works when nobody is watching.",
        "If approval happens after the fact, call it what it is.",
        "Management override is not a feature.",
        "The control owner needs training, not vibes.",
        "A quarterly control cannot live on annual memory.",
        "The exception is small; the pattern is not.",
        "The control failed quietly, which is its favorite way.",
        "If access is excessive, the spreadsheet is not the villain.",
        "The reviewer signed, but did they review?",
        "Evidence of review should show a review.",
        "The SOX deadline does not care about your narrative arc.",
        "Compensating control is not a magic spell.",
        "If one person prepares and approves, invite segregation of duties.",
        "A timestamp can be more honest than a paragraph.",
        "The walkthrough is where the story starts sweating.",
        "A control without an owner is a wish.",
        "The answer is a deficiency until proven otherwise.",
        "Retest before optimism becomes documentation.",
        "The design may pass; the operation is sulking.",
        "The control is effective only if reality attended the meeting.",
        "Hide columns, find secrets.",
        "The formula did not break itself.",
        "If VLOOKUP is involved, light a small candle.",
        "The pivot table is telling the truth in a difficult accent.",
        "Copy-paste values: where evidence goes to become folklore.",
        "The spreadsheet is innocent until the filters appear.",
        "If the total ties, check the subtotal anyway.",
        "The answer is in row 1048576, emotionally.",
        "Color coding is not methodology.",
        "Freeze panes, not your judgment.",
        "The macro may be useful; the fear is reasonable.",
        "Excel says yes; reconciliation says not so fast.",
        "If it only works on one laptop, it does not work.",
        "The hidden tab is not hidden from consequences.",
        "A broken link is a confession.",
        "The cell someone hardcoded is waving.",
        "The workbook needs version control and a nap.",
        "Do not trust a model that requires ritual opening.",
        "The variance is not rounding just because it is annoying.",
        "The spreadsheet will confess after you remove the filters.",
        "The review note is annoying because it is right.",
        "Clear the comment, not just the color.",
        "If you disagree, document the disagreement like an adult.",
        "The partner question is shorter than the answer it deserves.",
        "Review notes multiply in the dark.",
        "The second reviewer is not attacking you; probably.",
        "Answer the question asked, not the one you prefer.",
        "A resolved note without evidence is decorative.",
        "If the comment says please clarify, clarify.",
        "The note can be closed after the logic can stand alone.",
        "Do not reply done to a conceptual issue.",
        "The reviewer found the loose thread; pull it.",
        "Your explanation got longer because the evidence got weaker.",
        "Keep the tone kind and the citation precise.",
        "A good tickmark prevents three emails.",
        "The answer is not see above if above is fog.",
        "The note is a gift wrapped in inconvenience.",
        "Close it today or meet it again at midnight.",
        "Review is where assumptions go to get weathered.",
        "The best response is boring, complete, and sourced.",
        "Immaterial does not mean invisible.",
        "The amount is small; the cause is interesting.",
        "One exception is a finding's first draft.",
        "Aggregate before declaring victory.",
        "If it repeats, it is no longer adorable.",
        "Materiality is not a personality shield.",
        "The difference is below threshold and above peace.",
        "Document why it does not matter, especially if it annoys you.",
        "Trivial errors love becoming trends.",
        "The exception log is not a graveyard.",
        "If it changes the story, it matters.",
        "Waive it only after you understand it.",
        "The finding is not material yet, but it has ambition.",
        "Small numbers can point to large habits.",
        "The answer is pass further, not pretend absent.",
        "If management shrugs, write down the shrug.",
        "An isolated issue should not need a family reunion.",
        "The pattern has entered the chat.",
        "The conclusion should mention both size and cause.",
        "Do not let immaterial become undocumented.",
        "Coffee first, signoff second.",
        "The deadline is real; the panic is optional.",
        "File before the portal closes.",
        "Friday at 5 p.m. is not a governance model.",
        "If it arrives after midnight, it gets morning judgment.",
        "The calendar says no because you would not.",
        "A tired conclusion is still a conclusion, but test it.",
        "The answer can wait until coffee; the cache cannot.",
        "Do not open a new issue after lunch unless it brings snacks.",
        "The deadline needs a plan, not a heroic monologue.",
        "If everyone is tired, add one more review.",
        "Archive while you still remember what happened.",
        "The workpaper is due before your soul leaves the building.",
        "Send the status update before the status becomes fiction.",
        "The best time to ask was yesterday; the second best is now.",
        "Do the hard file first; it has teeth.",
        "The clock is a control deficiency in disguise.",
        "End the meeting before it becomes evidence.",
        "A clean close is better than a dramatic save.",
        "Book the review before the reviewer disappears.",
        "Ask IT, then ask where IT got that answer.",
        "Management's confidence is not a population.",
        "Per management is a starting point, not a conclusion.",
        "If IT says expected behavior, ask whose expectation.",
        "The system generated it, but who blessed the system?",
        "Management accepted the risk; keep the receipt.",
        "A dashboard is not evidence unless you know its kitchen.",
        "The access list is asking for adult supervision.",
        "ITGC is not a mood, unfortunately.",
        "If the report is canned, find the can opener.",
        "The data owner is whoever stops replying last.",
        "Management representation is not a time machine.",
        "Ask for the query, not the screenshot of the query.",
        "If the report changed, so did the question.",
        "The answer lives between business owner and system owner.",
        "Do not let system limitation end the conversation.",
        "The control owner knows less than the log.",
        "If nobody owns the report, nobody owns the comfort.",
        "Management's explanation needs a source, not a blazer.",
        "IT will answer eventually; document the silence meanwhile.",
        "Sign off only when future you can defend it.",
        "The memo should explain the judgment, not your exhaustion.",
        "If it took three calls, it deserves three sentences.",
        "A conclusion without criteria is a wish in PDF.",
        "The workpaper should tell the story without you in the room.",
        "Archive the reasoning, not just the file.",
        "The signoff date should not time travel.",
        "Put the caveat where the partner will actually see it.",
        "The answer is memo, not meeting.",
        "If you cannot summarize it, you cannot sign it.",
        "A good conclusion has a spine.",
        "The tickmark should survive a stranger.",
        "Do not bury the risk in paragraph four.",
        "The memo is too long because the conclusion is shy.",
        "State the judgment before decorating it.",
        "If the evidence is messy, the memo must be clean.",
        "The signoff is not a forgiveness ritual.",
        "Write it like regulator you is bored and caffeinated.",
        "The conclusion needs criteria, condition, cause, effect.",
        "Close the loop, not just the tab.",
        "The issue belongs in the file, not in your bloodstream.",
        "This is a job, not a sacred vow to Excel.",
        "You are allowed to log off after documenting the risk.",
        "The workpaper will not love you back.",
        "Protect your calendar like audit evidence.",
        "If the task follows you home, give it an owner.",
        "Your anxiety is not a review procedure.",
        "The finding is real; so is dinner.",
        "Do not confuse responsiveness with usefulness.",
        "The laptop can sleep; so can you.",
        "Escalate before resentment becomes methodology.",
        "A control issue is not a character flaw.",
        "No one gets extra comfort from your burnout.",
        "The audit trail does not require your entire personality.",
        "Put the problem in the tracker, then leave it there.",
        "You can care without becoming the control.",
        "The answer is not in your fourth coffee.",
        "If the file needs a hero, the process needs redesign.",
        "Rest is not scope limitation.",
        "Close your laptop before your judgment gets material.",
        "Escalate early while the issue is still polite.",
        "Scope creep is wearing a reasonable outfit.",
        "If the question changes the audit, bring a manager.",
        "Do not accept ownership by silence.",
        "The issue is bigger than your lane; use the road signs.",
        "A clear escalation is kinder than a private panic.",
        "Put it on the risk register before it puts you there.",
        "If it affects conclusion, it deserves daylight.",
        "Do not solve a governance problem with extra hours.",
        "The answer is out of scope until someone signs otherwise.",
        "Boundaries apply to audits too.",
        "If the client wants more work, the fee should hear about it.",
        "The new request needs a change order, not a sigh.",
        "Bring the fact pattern, not the feeling pattern.",
        "Escalation is documentation with a ladder.",
        "If nobody wants to own it, that is the issue.",
        "The scope line is faint because people keep stepping on it.",
        "Ask what decision this work supports.",
        "If the answer will not change the opinion, question the work.",
        "Stop before just one more test becomes a lifestyle.",
        "The audit spirit says: screenshot, then breathe.",
        "The printer is not material, but it is hostile.",
        "Your sample has main character energy.",
        "The evidence folder is practicing minimalism.",
        "The confirmation is lost somewhere between hope and spam.",
        "The binder is organized by vibes and fear.",
        "The workpaper passed, but only because it learned manners.",
        "The file path is longer than the procedure.",
        "The client portal has chosen violence.",
        "The status meeting could have been a tickmark.",
        "The exception log is whispering your name.",
        "Someone named the file final final real final, and that is evidence.",
        "The answer is in the email you already searched twice.",
        "The report ran successfully, which is suspicious.",
        "The audit universe demands one more screenshot.",
        "The chair knows what happened in busy season.",
        "This issue has become sentient; escalate.",
        "The PDF rotated itself to avoid accountability.",
        "The stapler understands materiality better than this process.",
        "The review note has returned from the dead.",
        "Recalculate it.",
        "Reconcile first, conclude second.",
        "Sample again.",
        "Expand testing.",
        "Reduce testing, but document why.",
        "Ask for original support.",
        "Walk it through end to end.",
        "Tie it to the GL.",
        "Confirm externally.",
        "Observe the process yourself.",
        "Reperform the control.",
        "Challenge the assumption.",
        "Separate the preparer and reviewer.",
        "Update the risk assessment.",
        "Draft the finding.",
        "Clear the exception with evidence.",
        "Accept with caveat.",
        "Reject the support.",
        "Park it for manager review.",
        "Close it, but leave a breadcrumb."
      ]
    },
    "zh": {
      "name": "审计人生",
      "prompt": "想好你的审计难题，然后面对证据。",
      "hint": "点击查阅",
      "askBtn": "查阅档案",
      "againBtn": "重新抽样",
      "ornament": "§",
      "answers": [
        "证据不足，驳回",
        "发现范围蔓延，立即停止",
        "先咨询你的上级经理",
        "低于重要性水平，记录后继续",
        "交给审计委员会决定",
        "这个发现具有重大影响",
        "管理层已凌驾于控制之上",
        "请提供额外支持性证据",
        "不在已定义范围内",
        "据称存在替代性控制",
        "截止日期又延期了",
        "立即上报",
        "这是控制漏洞，不是你的人格缺陷",
        "据管理层称，系统按预期运行",
        "穿行测试讲了另一个故事",
        "重新计算，重新核对，再来一遍",
        "你的样本量不足",
        "例外已记录，继续前进",
        "这需要二次复核",
        "标记为下季度跟进",
        "管理层接受了风险，请保留证据",
        "金额不重大，但备忘录还是要写",
        "先放进停车场，和其他幽灵议题作伴",
        "先问 IT，再问 IT 的答案从哪来",
        "整改预计在下个财年",
        "你又超范围了",
        "电子表格在被筛选前都是清白的",
        "记录一切，谨慎信任",
        "这是一个重大缺陷",
        "先关账，问题以后再说",
        "PBC 清单又变长了",
        "需要重新执行测试",
        "未发现例外，罕见奇迹",
        "证据文件不完整",
        "三方匹配失败",
        "管理层声明书终于收到了",
        "你的发现将被管理层质疑",
        "发出询证函，然后祈祷",
        "SOX 截止日期不等人",
        "先喝咖啡，再做审计",
        "先证据，后自信。",
        "如果支持文件是糊的，结论也是糊的。",
        "没有日期的截图，是穿着正装的传闻。",
        "在故事变得动听之前，先要源数据。",
        "PDF 被锁住，是因为真相害怕 Excel。",
        "勾到源文件，否则放手。",
        "文件名说 final，元数据不同意。",
        "如果它来自记忆，它属于谈话，不属于底稿。",
        "证据差一点够，意思就是还不够。",
        "相信邮件之前，先打开附件。",
        "只有筛选后才一致，这不叫一致。",
        "在轨迹消失前，先保存轨迹。",
        "答案在没人提到的那个标签页里。",
        "如果不能重新执行，就不要浪漫化它。",
        "文件存在，证据不存在。",
        "问是谁准备的，也问谁害怕准备它。",
        "如果没人读过，签名就不是控制。",
        "发票很有感觉，但先要日期。",
        "证据应该减少戏剧性，而不是创造神话。",
        "把源链接放在未来的你找得到的地方。",
        "PBC 清单进入了反派时期。",
        "清楚地问一次；追第二次最好有经理加持。",
        "客户不是忘了，他们只是优先安排了你的痛苦。",
        "如果你想在后悔前收到，就中午前发请求。",
        "PBC 据说是 Please Be Calm。",
        "礼貌跟进不是骚扰，是审计天气。",
        "如果客户说马上发，启动计时器，不要开始祈祷。",
        "丢失的文件大概率叫 New Folder 7。",
        "解释经得起一次追问之后，再接受。",
        "客户电话需要议程，也需要出口匝道。",
        "如果他们回答了除问题以外的一切，就上报。",
        "第三次提醒应该用项目符号。",
        "不要让亲切代替支持文件。",
        "请求很清楚，回复像现代舞。",
        "要一个负责人。人群不会上传证据。",
        "延迟本身就是一个数据点。",
        "友好的客户也可能给出不可用证据。",
        "答案是 pending，也就是审计版的闹鬼。",
        "在记忆改稿之前，把请求写下来。",
        "今天的 PBC 奇迹，会变成明天的复核意见。",
        "没人看着时也能运行的控制，才算运行。",
        "如果批准发生在事后，就照实命名。",
        "管理层凌驾不是功能。",
        "控制负责人需要培训，不需要感觉。",
        "季度控制不能靠年度记忆活着。",
        "例外很小，模式不小。",
        "控制安静地失败了，这是它最喜欢的方式。",
        "如果权限过度，表格就不是反派。",
        "复核人签了，但复核了吗？",
        "复核证据应该看得出复核。",
        "SOX 截止日期不在乎你的叙事弧光。",
        "补偿性控制不是魔法咒语。",
        "如果同一个人准备又批准，请邀请职责分离登场。",
        "时间戳可能比一段话更诚实。",
        "穿行测试是故事开始冒汗的地方。",
        "没有负责人的控制，只是一个愿望。",
        "在证明相反之前，答案就是缺陷。",
        "在乐观变成文档之前，先重新测试。",
        "设计可能通过了，运行正在闹别扭。",
        "只有现实也参加了会议，控制才算有效。",
        "隐藏列，发现秘密。",
        "公式不是自己坏的。",
        "如果涉及 VLOOKUP，请点一支小蜡烛。",
        "数据透视表正在用奇怪口音讲真话。",
        "复制粘贴数值：证据变成民间传说的地方。",
        "筛选出现前，表格都是无辜的。",
        "总数勾上了，也请检查小计。",
        "从情绪上说，答案在第 1048576 行。",
        "颜色编码不是方法论。",
        "冻结窗格，不要冻结判断。",
        "宏可能有用，害怕也合理。",
        "Excel 说可以，调节表说别急。",
        "如果它只在一台电脑上能跑，那就不算能跑。",
        "隐藏标签页躲不过后果。",
        "断掉的链接是一种供认。",
        "那个被硬编码的单元格正在挥手。",
        "这个工作簿需要版本控制和午睡。",
        "不要信任一个需要仪式感才能打开的模型。",
        "差异不会因为烦人就自动变成四舍五入。",
        "去掉筛选之后，表格会招供。",
        "复核意见烦人，是因为它是对的。",
        "清掉问题，不只是清掉颜色。",
        "如果不同意，就像成年人一样记录分歧。",
        "合伙人的问题很短，但它配得上很长的答案。",
        "复核意见会在黑暗中繁殖。",
        "第二复核人不是在攻击你，大概吧。",
        "回答被问的问题，不是你喜欢的问题。",
        "没有证据的已解决意见，只是装饰。",
        "如果意见写着请澄清，那就澄清。",
        "逻辑能独立站住之后，意见才能关闭。",
        "不要用 done 回复概念性问题。",
        "复核人找到了线头，把它拉出来。",
        "解释变长，是因为证据变弱了。",
        "语气保持友好，引用保持精准。",
        "一个好勾稽符号能避免三封邮件。",
        "如果上面是一团雾，答案就不能是见上。",
        "这条意见是裹着不便的礼物。",
        "今天关掉它，否则半夜再见它。",
        "复核是让假设接受风吹雨打的地方。",
        "最好的回复是无聊、完整、有来源。",
        "不重大不等于看不见。",
        "金额很小，原因很有意思。",
        "一个例外，是一个发现的初稿。",
        "宣布胜利之前，先汇总。",
        "如果它反复出现，就不可爱了。",
        "重要性水平不是人格护盾。",
        "差异低于阈值，高于平静。",
        "写明它为什么不重要，尤其当它很烦人。",
        "小错误很爱长成趋势。",
        "例外事项清单不是墓地。",
        "如果它改变故事，它就重要。",
        "只有理解之后，才可以豁免。",
        "这个发现还不重大，但它很有野心。",
        "小数字能指向大习惯。",
        "答案是进一步通过，不是假装不存在。",
        "如果管理层耸肩，把耸肩写下来。",
        "孤立问题不该需要全家团聚。",
        "模式已经进入聊天。",
        "结论应该同时写金额和原因。",
        "不要让不重大变成不记录。",
        "先咖啡，后签字。",
        "截止日期是真的，慌张是可选的。",
        "在传送门关闭前归档。",
        "周五下午五点不是治理模型。",
        "如果它半夜到达，就交给早晨判断。",
        "日历说不，是因为你不会说。",
        "疲惫的结论仍是结论，但请测试它。",
        "答案可以等咖啡，缓存不行。",
        "午饭后不要开新问题，除非它带零食。",
        "截止日期需要计划，不需要英雄独白。",
        "如果所有人都累了，就再加一次复核。",
        "趁你还记得发生了什么，赶紧归档。",
        "在灵魂离开大楼前，底稿先到期。",
        "在状态变成小说前，先发状态更新。",
        "最好的提问时间是昨天，第二好是现在。",
        "先做难文件，它有牙齿。",
        "时钟是伪装成时间的控制缺陷。",
        "在会议变成证据前结束它。",
        "干净关闭胜过戏剧化拯救。",
        "在复核人消失前，把复核约上。",
        "先问 IT，再问 IT 的答案从哪来。",
        "管理层的自信不是总体。",
        "根据管理层说法是起点，不是结论。",
        "如果 IT 说这是预期行为，问是谁的预期。",
        "系统生成了它，但谁祝福了系统？",
        "管理层接受了风险，请保留小票。",
        "除非你知道厨房在哪，否则仪表盘不是证据。",
        "权限清单正在要求成年人监督。",
        "很遗憾，ITGC 不是一种心情。",
        "如果报告是罐头，先找到开罐器。",
        "数据负责人就是最后停止回复的人。",
        "管理层声明不是时光机。",
        "要查询语句，不要查询语句的截图。",
        "如果报告变了，问题也变了。",
        "答案住在业务负责人和系统负责人之间。",
        "不要让系统限制结束谈话。",
        "控制负责人知道的还不如日志多。",
        "如果没人拥有报告，也没人拥有安慰。",
        "管理层解释需要来源，不需要西装外套。",
        "IT 终会回复；在此期间记录沉默。",
        "只有未来的你能 defend 时，才签字。",
        "备忘录应该解释判断，不是解释你有多累。",
        "如果它花了三通电话，就值得三句话。",
        "没有标准的结论，是 PDF 里的愿望。",
        "即使你不在房间里，底稿也应该能讲清故事。",
        "归档推理，不只是归档文件。",
        "签字日期不该穿越时空。",
        "把保留意见放在合伙人真的会看到的地方。",
        "答案是备忘录，不是会议。",
        "如果你总结不了，就不能签。",
        "好结论有脊梁。",
        "勾稽符号应该能经得起陌生人阅读。",
        "不要把风险埋在第四段。",
        "备忘录太长，是因为结论害羞。",
        "先写判断，再做装饰。",
        "证据越乱，备忘录越要干净。",
        "签字不是宽恕仪式。",
        "像一个无聊且咖啡因充足的监管版自己那样写。",
        "结论需要标准、状况、原因、影响。",
        "关掉闭环，不只是关掉标签页。",
        "问题属于文件，不属于你的血液。",
        "这是一份工作，不是对 Excel 的神圣誓言。",
        "记录风险之后，你可以下线。",
        "底稿不会爱你。",
        "像保护审计证据一样保护你的日历。",
        "如果任务跟你回家，就给它一个负责人。",
        "你的焦虑不是复核程序。",
        "发现是真的，晚饭也是真的。",
        "不要把反应快误认为有用。",
        "电脑可以睡，你也可以。",
        "在怨气变成方法论之前上报。",
        "控制问题不是人格缺陷。",
        "没人会从你的燃尽里获得额外安慰。",
        "审计轨迹不需要你的整个人格。",
        "把问题放进 tracker，然后让它待在那里。",
        "你可以在乎，但不必变成控制本身。",
        "答案不在你的第四杯咖啡里。",
        "如果文件需要英雄，流程就需要重设。",
        "休息不是范围限制。",
        "在你的判断变重大之前，先合上电脑。",
        "趁问题还礼貌，早点上报。",
        "范围蔓延穿着一身合理的衣服。",
        "如果问题改变审计，就带上经理。",
        "不要用沉默接受所有权。",
        "这个问题比你的车道更大，请看路标。",
        "清楚上报比私下慌张更温柔。",
        "在它把你放进去之前，先把它放进风险登记册。",
        "如果它影响结论，就值得见光。",
        "不要用加班解决治理问题。",
        "在有人签字改口之前，答案是超范围。",
        "边界也适用于审计。",
        "如果客户想要更多工作，费用也该听见。",
        "新请求需要变更单，不是一声叹气。",
        "带事实模式来，不要只带感受模式。",
        "上报是带梯子的文档。",
        "如果没人想拥有它，那就是问题。",
        "范围线之所以淡，是因为大家一直踩。",
        "问问这项工作支持哪个决定。",
        "如果答案不会改变意见，就质疑这项工作。",
        "在再测一个变成生活方式之前停下。",
        "审计之灵说：先截图，再呼吸。",
        "打印机不重大，但它有敌意。",
        "你的样本很有主角感。",
        "证据文件夹正在练习极简主义。",
        "函证迷失在希望和垃圾邮件之间。",
        "文件夹按感觉和恐惧组织。",
        "底稿通过了，只因为它学会了礼貌。",
        "文件路径比程序还长。",
        "客户门户选择了暴力。",
        "状态会议本可以是一个勾稽符号。",
        "例外事项清单正在低声叫你的名字。",
        "有人把文件命名为 final final real final，这本身就是证据。",
        "答案在你已经搜过两次的邮件里。",
        "报告成功运行了，这很可疑。",
        "审计宇宙要求再来一张截图。",
        "椅子知道忙季发生了什么。",
        "这个问题已经有自我意识了，上报。",
        "PDF 自己旋转，是为了逃避问责。",
        "订书机比这个流程更懂重要性。",
        "复核意见从死里回来了。",
        "重新计算它。",
        "先调节，后下结论。",
        "重新抽样。",
        "扩大测试。",
        "减少测试，但写明原因。",
        "索取原始支持文件。",
        "从头到尾穿行一遍。",
        "勾到总账。",
        "外部函证。",
        "亲自观察流程。",
        "重新执行控制。",
        "挑战假设。",
        "分离编制人和复核人。",
        "更新风险评估。",
        "起草发现。",
        "用证据清除例外。",
        "带保留接受。",
        "驳回支持文件。",
        "暂放给经理复核。",
        "关闭它，但留下面包屑。"
      ]
    }
  },
  "relationship": {
    "en": {
      "name": "The Heart Speaks",
      "prompt": "Hold your heart's question gently, then listen.",
      "hint": "tap to listen",
      "askBtn": "Ask Your Heart",
      "againBtn": "Ask Again",
      "ornament": "♡",
      "answers": [
        "There may be warmth here, but watch their effort",
        "This chapter is asking for an honest ending",
        "A new connection needs space to find you",
        "Give it time, but not your whole life",
        "Your heart knows more when it feels safe",
        "Communication is the kindest way forward",
        "Let them meet you halfway",
        "This is worth effort only if it is mutual",
        "Walk away before resentment teaches you how",
        "Love yourself loudly enough to hear it",
        "The timing needs more truth",
        "Do not build certainty from crumbs",
        "Distance is giving you useful information",
        "Your feelings are valid; your next step still matters",
        "They may be meaningful without being right for you",
        "Be vulnerable where care has been proven",
        "Reach out once, clearly and calmly",
        "A reunion would need new behavior",
        "A boundary will tell you what love cannot",
        "The connection is real; so are your needs",
        "You deserve steadiness, not suspense",
        "Forgive only at the pace your body allows",
        "Take space before you make a vow",
        "Trust grows in repeated small moments",
        "Love returned late is still allowed to be questioned",
        "This is a lesson if it keeps shrinking you",
        "They may want to hear from you; you still need clarity",
        "One more chance needs one new agreement",
        "You are enough without earning someone's attention",
        "Love is not the same as waiting",
        "Feel it fully, then choose wisely",
        "Do not wait for someone who keeps choosing absence",
        "Your next love begins with your next honest no",
        "Protect your tenderness from careless hands",
        "Say the sentence you keep rehearsing",
        "This relationship needs air, not pressure",
        "You cannot love someone into readiness",
        "The red flags are asking to be believed",
        "Your intuition deserves a seat at the table",
        "End it kindly if staying makes you unkind to yourself",
        "Ask clearly, then stop interpreting shadows.",
        "Say the thing before your silence becomes a test.",
        "The next message should be honest, not perfect.",
        "Do not send the paragraph that is secretly a trial.",
        "One calm question will teach you more than ten rereads.",
        "If you need clarity, ask for clarity.",
        "Let the conversation happen in daylight.",
        "Your tone can be kind without hiding the truth.",
        "Say it once without performing detachment.",
        "The right words are fewer than the rehearsed ones.",
        "Ask what this is, not what it could become.",
        "A brave sentence is better than a beautiful hint.",
        "Do not outsource the talk to timing.",
        "The answer will come through how they respond to directness.",
        "Send the message you can respect tomorrow.",
        "Stop using silence as a courtroom.",
        "Ask them, not your anxiety.",
        "Make the invitation simple enough to accept or refuse.",
        "The truth needs a table, not a stage.",
        "Talk before the story hardens.",
        "Watch effort, not electricity.",
        "Mutual should not feel like a miracle.",
        "If you are always reaching, you are already being answered.",
        "Care that cannot move toward you is only weather.",
        "Let them cross some distance too.",
        "A real yes has legs.",
        "If the warmth is real, it will learn a schedule.",
        "Do not turn potential into a full-time job.",
        "Love should not require constant translation.",
        "Notice who repairs, not who regrets.",
        "Their interest needs behavior.",
        "If they want closeness, they can participate.",
        "You are not difficult for wanting equal effort.",
        "A connection is not mutual because it is intense.",
        "Wait for proof that arrives without begging.",
        "The answer is in what they do when it is inconvenient.",
        "Do not carry the whole bridge.",
        "Let consistency be the love language.",
        "If they keep you guessing, choose the fact of that.",
        "Mutual care feels calmer than pursuit.",
        "Love needs a door, not a leak.",
        "Keep your boundary even if your heart shakes.",
        "The line is kind because it is clear.",
        "Access is earned again slowly.",
        "If the boundary ends the bond, the bond was using you.",
        "Say no before your body says it for you.",
        "You can miss them and still protect yourself.",
        "A boundary is not a punishment.",
        "Stop offering premium access to uncertain care.",
        "Your peace is allowed to have rules.",
        "The right person will not need you boundaryless.",
        "Do not negotiate the minimum.",
        "Let the boundary be short and real.",
        "Your softness needs a gate.",
        "The answer is less access, more truth.",
        "If they push the line, believe the push.",
        "Keep one room inside you that nobody can enter casually.",
        "A loving choice can still be a closed door.",
        "You are not cruel for ending the audition.",
        "The boundary is the answer wearing shoes.",
        "You do not have to earn being chosen.",
        "Stop auditioning for a role that should be offered.",
        "You are not too much; this may be too little.",
        "Do not make their confusion your mirror.",
        "Your value is not waiting for their reply.",
        "The right love will not ask you to disappear.",
        "Wanting steadiness is not neediness.",
        "You are not a lesson someone gets to keep hurting.",
        "Love yourself louder than the maybe.",
        "Do not shrink to fit someone's uncertainty.",
        "You can be lovable and still leave.",
        "Your dignity is not the price of intimacy.",
        "If you feel smaller every week, believe the measurement.",
        "You are not the backup plan for someone's fear.",
        "The answer begins where self-abandonment ends.",
        "Your tenderness is not a coupon.",
        "They can be good and still not good for you.",
        "You do not need to become easier to love.",
        "The right person will recognize your humanity, not just your availability.",
        "Choose the version of you that can breathe.",
        "Give it time, but set a timer.",
        "Not now is an answer when repeated.",
        "The timing is wrong if honesty keeps being postponed.",
        "A delayed reply is data, not destiny.",
        "Let time reveal behavior, not excuse it.",
        "If it is real, it can survive a slower pace.",
        "Do not rush a bond that cannot stand still.",
        "The next season will clarify what this one romanticizes.",
        "Wait for calm, not for obsession.",
        "The right timing will include both of you.",
        "If they are not ready, do not become their waiting room.",
        "Time can help; it cannot do the talking.",
        "The pause is useful only if it changes something.",
        "Give this one full week of observation.",
        "A reunion before growth is repetition.",
        "Do not confuse timing with avoidance.",
        "Let slow be healthy, not indefinite.",
        "The answer will be clearer after one ordinary day together.",
        "If the window never opens, stop living at it.",
        "The heart can wait; your life should not freeze.",
        "Believe the pattern before the promise.",
        "The red flag is not asking to be understood; it is asking to be believed.",
        "A soft apology cannot erase hard repetition.",
        "If you are explaining away pain, pause.",
        "Inconsistency is information.",
        "Mixed signals are signals.",
        "Do not call it complicated if it is simply careless.",
        "If their affection disappears under pressure, notice.",
        "The warning is kind when it arrives early.",
        "Your body flinched before your mind negotiated.",
        "If they punish honesty, step back.",
        "Charm is not repair.",
        "The beautiful moments do not cancel the cruel ones.",
        "If you feel managed, not met, pay attention.",
        "The excuse has become a pattern.",
        "Do not decorate the red flag until it matches the room.",
        "Love without responsibility is weather.",
        "When someone shows you the cost, do the math.",
        "If you are afraid to ask, that matters.",
        "The answer is already in what you keep minimizing.",
        "You can forgive without returning.",
        "Healing is not a group project with the person who hurt you.",
        "Let grief move, but do not let it drive.",
        "Closure may be something you give yourself.",
        "The wound needs care, not surveillance.",
        "Stop checking the place that bruised you.",
        "You are allowed to heal without proving you were hurt.",
        "Missing them is not a command.",
        "The ache will not always be the loudest thing.",
        "Let the body unclench before deciding.",
        "Do not make pain meaningful just to make it bearable.",
        "Rest from the story.",
        "You can be sad and correct.",
        "The heart is catching up to the facts.",
        "Let the lesson be gentle now.",
        "The answer is recovery, not revenge.",
        "Grieve the hope too.",
        "You do not have to keep touching the bruise.",
        "Peace may feel boring after chaos; choose it anyway.",
        "Healing starts when you stop cross-examining yourself.",
        "You miss a version, not the whole truth.",
        "Nostalgia is editing the footage.",
        "The memory is warm; the pattern was not.",
        "Do not date the highlight reel.",
        "The past is allowed to be beautiful and over.",
        "What you miss may be who you were while hoping.",
        "The old chemistry still needs new behavior.",
        "A familiar ache is not a home.",
        "The story was real; so was the ending.",
        "Do not confuse unfinished with meant to be.",
        "The door behind you has changed locks.",
        "You can honor the memory without reopening the wound.",
        "The longing will pass through if you stop feeding it.",
        "The sweetest scene was not the whole movie.",
        "They may miss you and still not meet you.",
        "Old love needs present evidence.",
        "The past is knocking; you do not have to answer.",
        "Let the good parts stay good without making them guidance.",
        "You are not betraying the memory by choosing peace.",
        "The answer is not back there.",
        "A second chance needs a new structure.",
        "Try again only if the behavior changed before the promise.",
        "Do not re-enter without a different agreement.",
        "The door can open, but not to the same room.",
        "Apology is the entrance fee, not the repair.",
        "If you return, return with your boundary intact.",
        "This can be rebuilt, but not on denial.",
        "Watch what they do with the chance, not how they ask for it.",
        "One more chance needs one less excuse.",
        "If the same wound is waiting, do not call it hope.",
        "The answer is maybe, with terms.",
        "Let repair be measurable.",
        "Do not reward disappearance with instant access.",
        "If they learned, it will show in small logistics.",
        "A new beginning needs new habits.",
        "Make the agreement plain.",
        "If they resist accountability, the chance is not ready.",
        "Forgiveness can open your heart without opening your calendar.",
        "A reunion should feel steadier, not just sweeter.",
        "The next try must protect the lesson.",
        "End it before you become unkind to yourself.",
        "The goodbye can be soft and final.",
        "Leaving is not failure when staying requires self-erasure.",
        "Do not wait until love turns into resentment.",
        "The ending is sad, not wrong.",
        "Let the door close without a courtroom.",
        "You can leave while still caring.",
        "Some chapters end because they told the truth.",
        "The answer is a clean ending, not a louder argument.",
        "Stop asking a closed hand to hold you.",
        "The grief is real; so is the release.",
        "Make the ending honest enough to heal from.",
        "If you must beg for care, go.",
        "The last conversation does not need to solve the whole story.",
        "Let it end before it teaches you bitterness.",
        "Choose the loss that returns you to yourself.",
        "The door is closing because you finally stopped holding it.",
        "Say goodbye to the pattern, not only the person.",
        "The answer is not punishment; it is completion.",
        "Leave with your tenderness still intact.",
        "Make room before you invite someone in.",
        "New love needs space, not comparison.",
        "Say yes slowly.",
        "Let curiosity lead before fantasy takes over.",
        "The beginning is good; keep your feet on the floor.",
        "Do not make them pay for someone else's absence.",
        "Let them show you who they are in small weather.",
        "The spark is welcome; look for steadiness too.",
        "This could grow if you do not grip it.",
        "Ask less are they the one and more do I feel safe.",
        "A healthy beginning may feel unfamiliar.",
        "Let easy be allowed.",
        "Do not rush naming what is still becoming.",
        "Watch how they handle a simple no.",
        "The answer is open, but not surrendered.",
        "Let the connection earn your imagination.",
        "A new chapter should not require old panic.",
        "Keep your friends, your rituals, and your center.",
        "This may be worth exploring gently.",
        "The first green flag is peace.",
        "Your body already knows something your hope is debating.",
        "The calm part of you is telling the truth.",
        "If your chest tightens every time, listen.",
        "The answer lives in the pattern, not the exception.",
        "You know the difference between butterflies and dread.",
        "Stop asking strangers to overrule your body.",
        "The dream is not the answer; your waking feeling is.",
        "Notice what you hide from your friends.",
        "If you cannot relax around them, do not call it mystery.",
        "Your intuition is quiet because it is not trying to win.",
        "The question keeps returning because the answer has not been honored.",
        "What you defend most may need the closest look.",
        "The sign is how you feel after seeing them.",
        "The answer is not in their potential; it is in your peace.",
        "Believe the part of you that feels sober.",
        "If you dread the notification, that is information.",
        "Your body is not being dramatic; it is keeping minutes.",
        "The truth may be simple enough to scare you.",
        "The quiet no deserves respect.",
        "The quiet yes deserves time.",
        "Reach out once.",
        "Do not reach out tonight.",
        "Ask for clarity.",
        "Wait for them to show effort.",
        "Take space.",
        "End it kindly.",
        "Say yes to the date, not the fantasy.",
        "Say no to the pattern.",
        "Forgive, but do not reopen.",
        "Reopen only with terms.",
        "Stop checking.",
        "Let them miss you without managing it.",
        "Tell the truth.",
        "Listen to the answer.",
        "Choose your peace.",
        "Ask what you need.",
        "Believe the behavior.",
        "Protect the soft part.",
        "Leave the door closed.",
        "Begin again with yourself."
      ]
    },
    "zh": {
      "name": "心语",
      "prompt": "轻轻怀抱你内心的疑问，然后聆听。",
      "hint": "点击聆听",
      "askBtn": "问问内心",
      "againBtn": "再问一次",
      "ornament": "♡",
      "answers": [
        "这里也许有温度，但要看对方的行动",
        "这一章正在请求一个诚实的收尾",
        "新的连接需要空间来靠近你",
        "给它时间，但不要交出你的整个人生",
        "当你感到安全时，心会知道更多",
        "沟通是最温柔的前进方式",
        "让对方也走向你一半",
        "只有彼此都投入，这才值得努力",
        "在怨气替你学会之前，先离开",
        "爱自己，要爱到自己听得见",
        "时机还需要更多真实",
        "不要用碎屑拼出确定感",
        "距离正在给你有用的信息",
        "你的感受成立，但下一步依然重要",
        "他们可以有意义，但未必适合你",
        "在关心已被证明的地方袒露脆弱",
        "联系一次，清楚而平静地说",
        "重聚需要新的行为来支撑",
        "边界会告诉你爱说不出的事",
        "连接是真的，你的需求也是真的",
        "你值得稳定，而不是悬念",
        "按身体允许的速度去原谅",
        "在许诺之前，先给自己空间",
        "信任生长在一次次小事里",
        "迟来的回应也可以被追问",
        "如果它让你越来越小，这就是一课",
        "他们也许想收到消息，但你仍需要清晰",
        "再给一次机会，需要一个新的约定",
        "不必赢得谁的注意，你也足够好",
        "爱不等于一直等待",
        "充分感受，然后明智选择",
        "不要等一个持续选择缺席的人",
        "下一段爱，始于你下一个诚实的拒绝",
        "把你的柔软从粗心的人手里保护出来",
        "说出那句你反复排练的话",
        "这段关系需要空气，而不是压力",
        "你不能靠爱让一个人准备好",
        "那些红旗正在请求你相信它们",
        "你的直觉应该被认真听见",
        "如果留下会让你亏待自己，就温柔结束",
        "清楚地问，然后停止解读影子。",
        "在沉默变成测试之前，把话说出来。",
        "下一条消息应该诚实，不必完美。",
        "不要发送那段其实是审判的长文。",
        "一个平静的问题，会比重读十遍教你更多。",
        "如果你需要清晰，就要清晰。",
        "让谈话发生在白天。",
        "你的语气可以温柔，也不必藏起真相。",
        "说一次，不要表演不在乎。",
        "正确的话，比排练过的话更少。",
        "问这是什么，不要只问它可能变成什么。",
        "一句勇敢的话，胜过一个漂亮暗示。",
        "不要把谈话外包给时机。",
        "答案会从他们如何回应直接里出现。",
        "发送那条明天的你仍会尊重的信息。",
        "不要把沉默当成法庭。",
        "去问他们，不要问你的焦虑。",
        "把邀请说得简单，简单到可以接受或拒绝。",
        "真相需要一张桌子，不需要舞台。",
        "在故事变硬之前谈一谈。",
        "看行动，不要只看电流感。",
        "相互不该像奇迹。",
        "如果总是你在伸手，答案已经出现了。",
        "不能走向你的在乎，只是天气。",
        "也让他们走一段距离。",
        "真正的可以有腿，会走路。",
        "如果温度是真的，它会学会出现在日程里。",
        "不要把潜力变成你的全职工作。",
        "爱不该需要持续翻译。",
        "看谁修复，不要只看谁后悔。",
        "他们的兴趣需要行动。",
        "如果他们想亲近，他们可以参与。",
        "想要同等努力，不代表你难搞。",
        "连接强烈，不等于相互。",
        "等待不需要乞求就会来的证据。",
        "答案在不方便时他们做什么。",
        "不要一个人扛整座桥。",
        "让稳定成为爱的语言。",
        "如果他们一直让你猜，就选择这个事实。",
        "相互的在乎，比追逐更安静。",
        "爱需要一扇门，不需要一个漏洞。",
        "即使心在抖，也守住边界。",
        "这条线是温柔的，因为它清楚。",
        "进入你的权限，要慢慢重新赢得。",
        "如果边界结束了关系，关系原本就在使用你。",
        "在身体替你说不之前，先说不。",
        "你可以想念他们，也仍然保护自己。",
        "边界不是惩罚。",
        "不要再给不确定的在乎高级权限。",
        "你的平静可以有规则。",
        "对的人不需要你没有边界。",
        "不要就最低限度讨价还价。",
        "让边界简短而真实。",
        "你的柔软需要一道门。",
        "答案是少一点权限，多一点真相。",
        "如果他们推那条线，请相信这个动作。",
        "在心里留一个没人能随便进入的房间。",
        "一个有爱的选择，也可以是一扇关上的门。",
        "结束试镜，并不代表你残忍。",
        "边界是穿上鞋的答案。",
        "你不必靠赚取才值得被选择。",
        "停止为一个本该被邀请的角色试镜。",
        "你不是太多，可能是这里太少。",
        "不要把他们的混乱当成你的镜子。",
        "你的价值不在等待他们回复。",
        "对的爱不会要求你消失。",
        "想要稳定不是黏人。",
        "你不是别人可以一直伤害的一堂课。",
        "爱自己，要比那个也许更响。",
        "不要缩小自己，去适应别人的不确定。",
        "你可以值得被爱，也仍然离开。",
        "你的尊严不是亲密的价格。",
        "如果你每周都感觉自己变小，请相信这个测量。",
        "你不是别人恐惧的备用方案。",
        "答案从自我放弃结束的地方开始。",
        "你的温柔不是优惠券。",
        "他们可以是好人，也仍然不适合你。",
        "你不需要变得更方便被爱。",
        "对的人会看见你的人性，而不只是你的可用性。",
        "选择那个能呼吸的自己。",
        "给它时间，但设一个计时器。",
        "反复出现的不是现在，本身就是答案。",
        "如果诚实一直被推迟，时机就是错的。",
        "延迟回复是数据，不是命运。",
        "让时间揭示行为，不要让时间替行为开脱。",
        "如果是真的，它经得起慢一点。",
        "不要催促一个连站稳都做不到的连接。",
        "下一个季节会澄清这个季节浪漫化的东西。",
        "等平静，不要等上瘾。",
        "对的时机里会有你们两个人。",
        "如果他们没准备好，不要变成他们的候诊室。",
        "时间可以帮忙，但不能替你说话。",
        "暂停只有在改变了什么时才有用。",
        "给这件事完整一周的观察。",
        "成长前的重逢只是重复。",
        "不要把时机和回避混为一谈。",
        "让慢变得健康，不要让它变成无限期。",
        "一起过一个普通日子之后，答案会更清楚。",
        "如果窗户从不开，就别住在窗边。",
        "心可以等，但你的人生不该冻结。",
        "先相信模式，再听承诺。",
        "红旗不是在请求被理解，它是在请求被相信。",
        "柔软的道歉擦不掉坚硬的重复。",
        "如果你正在替疼痛找解释，停一下。",
        "不稳定就是信息。",
        "混乱信号也是信号。",
        "如果只是粗心，就不要称它为复杂。",
        "如果他们的在乎一遇压力就消失，请留意。",
        "警告来得早，是一种温柔。",
        "在头脑谈判前，身体已经缩了一下。",
        "如果他们惩罚诚实，退后。",
        "魅力不是修复。",
        "美好的时刻不会抵消残忍的时刻。",
        "如果你感觉自己被管理，而不是被相遇，请留意。",
        "借口已经变成模式。",
        "不要把红旗装饰到适合这个房间。",
        "没有责任的爱只是天气。",
        "当有人让你看见代价，请算账。",
        "如果你害怕提问，这很重要。",
        "答案已经在你一直淡化的东西里。",
        "你可以原谅，而不必回去。",
        "疗愈不是和伤害你的人共同完成的小组作业。",
        "让悲伤流动，但不要让它开车。",
        "结束感可能是你给自己的东西。",
        "伤口需要照顾，不需要监视。",
        "停止反复查看那个撞伤你的地方。",
        "你可以疗愈，不必先证明自己受过伤。",
        "想念他们不是命令。",
        "疼痛不会永远是最响的东西。",
        "让身体先松开，再决定。",
        "不要为了让痛能忍，就强行赋予它意义。",
        "从这个故事里休息一下。",
        "你可以难过，也可以是对的。",
        "心正在追上事实。",
        "现在让这堂课温柔一点。",
        "答案是恢复，不是报复。",
        "也为那个希望难过一下。",
        "你不必一直触碰淤青。",
        "混乱之后，平静可能显得无聊；还是选它。",
        "当你停止盘问自己，疗愈就开始了。",
        "你想念的是一个版本，不是完整真相。",
        "怀旧正在剪辑素材。",
        "记忆是暖的，模式不是。",
        "不要和高光剪辑谈恋爱。",
        "过去可以美丽，也可以结束。",
        "你想念的，可能是那个还在期待的自己。",
        "旧日吸引仍然需要新的行为。",
        "熟悉的疼不是家。",
        "故事是真的，结束也是真的。",
        "不要把未完成误认为命中注定。",
        "你身后的门已经换锁了。",
        "你可以尊重记忆，而不必重新打开伤口。",
        "如果你停止喂养，想念会穿过去。",
        "最甜的那一幕不是整部电影。",
        "他们可能想念你，也仍然无法与你相遇。",
        "旧爱需要现在的证据。",
        "过去在敲门，你不必回应。",
        "让好的部分保持好，不必让它们成为指引。",
        "选择平静，不是在背叛记忆。",
        "答案不在后面。",
        "第二次机会需要新的结构。",
        "只有行为先于承诺改变，才再试一次。",
        "没有不同约定，就不要重新进入。",
        "门可以打开，但不能通向同一个房间。",
        "道歉是入场费，不是修复本身。",
        "如果回去，就带着完整边界回去。",
        "它可以重建，但不能建在否认上。",
        "看他们如何使用机会，不要只看他们如何请求机会。",
        "多一次机会，就要少一个借口。",
        "如果同一个伤口还在等着，就不要叫它希望。",
        "答案是也许，但有条件。",
        "让修复可以被看见和衡量。",
        "不要用立刻开放，奖励消失。",
        "如果他们学到了，会体现在小事安排里。",
        "新开始需要新习惯。",
        "把约定说清楚。",
        "如果他们抗拒负责，机会还没准备好。",
        "原谅可以打开你的心，不必打开你的日历。",
        "重逢应该更稳，而不只是更甜。",
        "下一次尝试必须保护这次学到的东西。",
        "在你开始对自己不温柔前结束它。",
        "告别可以柔软，也可以最终。",
        "如果留下需要抹掉自己，离开就不是失败。",
        "不要等到爱变成怨气。",
        "这个结束是难过的，不是错的。",
        "让门关上，不必开庭。",
        "你可以仍然在乎，也仍然离开。",
        "有些章节结束，是因为它们说了真话。",
        "答案是干净结束，不是更大声的争论。",
        "不要再要求一只握紧的手托住你。",
        "悲伤是真的，释放也是真的。",
        "让结束足够诚实，诚实到可以从中疗愈。",
        "如果你必须乞求在乎，就走。",
        "最后一场谈话不必解决整个故事。",
        "在它教会你苦涩之前，让它结束。",
        "选择那个让你回到自己的失去。",
        "门正在关上，是因为你终于不再撑着它。",
        "告别那个模式，不只是告别那个人。",
        "答案不是惩罚，是完成。",
        "带着仍然完整的温柔离开。",
        "邀请别人进来之前，先腾出空间。",
        "新爱需要空间，不需要比较。",
        "慢慢说可以。",
        "在幻想接管之前，让好奇带路。",
        "开始很好，但脚要留在地上。",
        "不要让他们为别人的缺席付账。",
        "让他们在小天气里展示自己是谁。",
        "火花很好，也要寻找稳定。",
        "如果你不抓太紧，它可能会生长。",
        "少问他们是不是唯一，多问我是否感到安全。",
        "健康的开始可能会陌生。",
        "允许容易发生。",
        "不要急着命名仍在形成的东西。",
        "看他们如何处理一个简单的不。",
        "答案是开放的，但不是投降。",
        "让连接赢得你的想象。",
        "新章节不该要求旧恐慌。",
        "保留你的朋友、仪式和中心。",
        "这值得温柔地探索。",
        "第一面绿旗是平静。",
        "你的身体已经知道某件事，而你的希望还在辩论。",
        "你内在平静的部分正在说真话。",
        "如果每次胸口都收紧，请听。",
        "答案住在模式里，不住在例外里。",
        "你知道心动和恐惧的区别。",
        "不要再请陌生人推翻你的身体。",
        "梦不是答案，醒来后的感觉才是。",
        "留意你对朋友隐瞒了什么。",
        "如果你在他们身边无法放松，就别称它为神秘。",
        "直觉很安静，因为它不是为了赢。",
        "问题反复回来，是因为答案还没被尊重。",
        "你最用力维护的东西，可能最需要近看。",
        "征兆是你见到他们之后的感觉。",
        "答案不在他们的潜力里，在你的平静里。",
        "相信那个清醒的自己。",
        "如果你害怕通知出现，那就是信息。",
        "你的身体不是戏多，它在做会议记录。",
        "真相可能简单到吓你一跳。",
        "安静的不值得尊重。",
        "安静的可以值得时间。",
        "联系一次。",
        "今晚不要联系。",
        "要一个清楚答案。",
        "等他们拿出行动。",
        "留出空间。",
        "温柔地结束它。",
        "对这次约会说可以，不是对幻想说可以。",
        "对这个模式说不。",
        "原谅，但不要重新打开。",
        "只有带着条件，才重新打开。",
        "停止查看。",
        "允许他们想念你，但不要替他们管理。",
        "说真话。",
        "听答案。",
        "选择你的平静。",
        "说出你需要什么。",
        "相信行为。",
        "保护柔软的部分。",
        "让门保持关闭。",
        "从自己这里重新开始。"
      ]
    }
  }
};
